### ISSUE TITLE
GDPR Breach

### ISSUE THREAD

**Issue by samip5** [oomessis/Bot#8]
Tämä kohta proceduurista on kyllä GDPR breach, koska viesti sisältöä ei saa tallentaa, eikä teidän tietosuoja selosteessa lue mitään viesti sisällön tallentamisesta. (Tietosuoja seloste: https://mess.is/wp-content/uploads/2019/04/Rekisteri-ja-tietosuojaseloste.pdf)
https://github.com/oomessis/Bot/blob/feeca9ef099e5a578287d351ee1c685567e14b21/SQL/up_upd_discord_messages.sql#L38

**Comment by Raybarg** [comment]
Compliance updated, Code does not give message content to procedure nor does procedure save the message content.
